### ISSUE TITLE
Относно търсене на субтитри в Easternspirit

### ISSUE THREAD

**Issue by martinstz** [ByJohnie/service.subtitles.modedbg#1]
Здравей, ByJohnie!
Чест и почитания!

Големи благодарности по работата ти върху добавката за субтитри! Много се радвам, че макар, поради неясни за мен причини, да напусна форума за Коди, не си спрял да твориш.
Имам едно запитване, относно търсенето на субтитри в Easternspirit. Има един филм "Till the End of the World", за който има субтитри в сайта, но добавката не вади резултати за него. Дали би могъл да погледнеш, защо?
Благодаря ти предварително и бих се радвал ако пак се завърнеш във форума!
Желая ти много здраве и успехи в личен и професионален план!

**Comment by ByJohnie** [comment]
ако ползваш тази добавка проблемът ти е локален, виж [тук](https://uc84b7199168d0bc8e386371117e.dl.dropboxusercontent.com/cd/0/get/AlmhJQLfqcb2NCkzyWsuatKx3wyQbPk0NMqjoRU4jocl1GDmByUq9j0I5haYiNw2DRwrulzmxe6lFPV29lMsQubx8BS1uHRS9V7DNfj2SvnAow/file?dl=1) или най вероятно си го забранил като търсене в опциите, другият вариант добавката през която гледаш филмът да ти дава грешно име за да не го намира

**Comment by martinstz** [comment]
Здравей пак!
Линкът, който си ми дал не е активен. Използвам Зелка или Замунда добавките за този филм. И ръчно да напиша името на филма пак не ми дава резултати. OpenSubtitles ми вади резултат. Сега констатирах, че на Андроид у-ва ми дава резултат, но на два компютъра с Windows, на които пробвам, не ми дава резултат.

**Comment by ByJohnie** [comment]
И на комп си работи без проблем [https://imgur.com/a/Oa8qhHg](https://imgur.com/a/Oa8qhHg)
и на андроид [link](https://www.dropbox.com/s/iho03gh2u8wpjgh/ScreenReord_2019-07-28-23-00-45.mp4?dl=0), нещо може да ти е омазано кодито много е бъгаво
